config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  get '/sign_in',  to: 'sessions#new'
  get '/sign_out', to: 'sessions#destroy'
  post 'sessions' => 'sessions#create' 

  get '/sign_up',  to: 'users#new'
  resources :users

  get 'posts/index'

  resources :posts

end

app/models/comment.rb
class Comment < ActiveRecord::Base 
	belongs_to :post

    def post
        Post.find(post_id)
    end 

end

app/models/post.rb
class Post < ActiveRecord::Base
has_many :comments

 #attr_accessor :title, :body

validates :title, :body, :presence => true

def comments
      Comment.where("post_id=#{id}")
end

def ultimo
     comments.last
end


end

app/models/user.rb
class User < ActiveRecord::Base

before_save :encrypt_password

  def self.authenticate(email, password_hash)
    user = User.where(email_string:email).first
    if user && user.password_hash == Digest::MD5.digest(password_hash).force_encoding("utf-8") 
      user
    else
      nil
    end
  end

  def encrypt_password
    if self.password_hash
      self.password_hash = Digest::MD5.digest(self.password_hash).force_encoding("utf-8") 
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  before_action :authenticate
  helper_method :current_user
  

  def new

    case self.klass

    when "Post"
      @post=Post.new
    when "User"
      @user=User.new 
    end
    
  end

  def current_user

    @user ||= @user=User.where(id:session[:user_id]).first

  end  

  
  def authenticate
    unless (session[:user_id])
      if (params[:controller] != "sessions" && params[:controller] != "users")
        redirect_to sign_in_path
      end
    end
  end



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts=Post.all.to_a
  end

 # def new
 #   @post=Post.new
 # end

  def create
     @post = Post.new(post_params)
   
    if @post.save
      redirect_to posts_path, :notice => "Post Guardado!"
    else
      render "new"
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end
  
  def show
    @post=Post.find(params[:id])
  end

  def post_params
      params.require(:post).permit(:title, :body)
  end

  def klass
     "Post"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

def create
  user = User.authenticate(params[:email], params[:password_hash])
  if user
    session[:user_id] = user.id
    redirect_to posts_path, :notice => "Logged in!"
  else
    flash.now.alert = "Invalid email or password"
    render "new"
  end
end

def destroy
  session[:user_id] = nil
  redirect_to posts_path, :notice => "Logged out!"
end

  def user_params
    params.require(:user).permit(:email_string, :password_hash)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
#  def new
#    @user = User.new
#  end

  # GET /users/1/edit
  def edit
  end

  def klass
     "User"
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update

    #@user.password_hash=Digest::MD5.digest(@user.password_hash).to_s.encode('UTF-8')

    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email_string, :password_hash)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h1>Editar</h1>

<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
	<% if @post.errors.any? %>
		<h2>Errores:</h2>	
		<ul>
			<% @post.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/posts/index.html.erb
<b><%= current_user.email_string %></b>
<%= link_to 'Log Out',sign_out_path %> | 
<%= link_to 'Nuevo Post', new_post_path %>
<h1>Blog</h1>
<% @posts.each do |post| %>

<h2>
<%= 
post.title.capitalize 
%> </h2>

<%= link_to 'Ver Post', post_path(post) %> | 
<%= link_to 'Editar', edit_post_path(post) %>
<p><%= post.body.titleize %></p>
<br>

<hr>
<% end %>

app/views/posts/new.html.erb
<h1>Nuevo post</h1>
 
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<h2>Errores:</h2>	
		<ul>
			<% @post.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>
<p>
	<%= f.label :title %><br />
	<%= f.text_field :title %><br />
<br />
	<%= f.label :body %><br />
	<%= f.text_area :body %>
</p>
<p>
	<%= f.submit "Agregar Nuevo Post" %>
</p>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email_string %><br>
    <%= f.text_field :email_string %>
  </div>
  <div class="field">
    <%= f.label :password_hash %><br>
    <%= f.text_field :password_hash %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Email string</th>
      <th>Password hash</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email_string %></td>
        <td><%= user.password_hash %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Sign UP</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email string:</strong>
  <%= @user.email_string %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>